# Generated by Django 4.2.3 on 2024-07-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_on_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
