# Generated by Django 4.2.3 on 2024-07-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('new', 'Yangi buyurtma'), ('ready', 'Dostavkaga tayyor'), ('waiting', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=9)),
                ('adress', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('viloyatni tanlang', 'Viloyatni tanlang'), ('andijan', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('fargana', "Farg'ona viloyati"), ('jizzakh', 'Jizzax viloyati'), ('namangan', 'Namangan viloyati'), ('navoi', 'Navoiy viloyati'), ('kashkadarya', 'Qashqadaryo viloyati'), ('republic of karakalpagistan', "Qoraqolpog'iston Respublikasi"), ('samarkand', 'Samarqand viloyati'), ('sirdarya', 'Sirdaryo viloyati'), ('surkhandarya', 'Surxondaryo viloyati'), ('tashkent', 'Toshkent'), ('khorezm', 'Xorazm viloyati')], max_length=27)),
                ('phone_number', models.CharField(max_length=13)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
