# Generated by Django 4.2.3 on 2024-07-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
